server:
  port: 8080

openvidu:
  url: https://49.50.139.108:4443/  # 설치한 미디어 서버 주소
  secret: openvidu010831


cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}  # 실제 키 대신 변수명 입력
      secret-key: ${NCP_SECRET_KEY}  # 실제 키 대신 변수명 입력
    s3:
      bucket: "live-commerce-bucket"      # 버킷 이름은 공개돼도 상관없음
      endpoint: "https://kr.object.ncloudstorage.com"
    region:
      static: "kr-standard" # 아까 .env에 설정한 그 비밀번호
    stack:
      auto: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livecommerce?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: mysql1234 # Mysql1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false # DB 커넥션 빨리 반납
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
#  data:
#    redis:
#      host: 10.0.1.8
#      port: 6379
#      password: redis1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.example.LiveHost: debug  # 우리 패키지 로그는 자세히(Debug) 보여줘
    org.hibernate.SQL: debug # 실행되는 SQL 쿼리도 보여줘