server:
  port: 8080

openvidu:
  url: https://49.50.139.108:4443/  # 설치한 미디어 서버 주소
  secret: openvidu010831


cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}  # 실제 키 대신 변수명 입력
      secret-key: ${NCP_SECRET_KEY}  # 실제 키 대신 변수명 입력
    s3:
      bucket: "live-vod-bucket"      # 버킷 이름은 공개돼도 상관없음
      endpoint: "https://kr.object.ncloudstorage.com"
    region:
      static: "kr-standard" # 아까 .env에 설정한 그 비밀번호
    stack:
      auto: false

#spring:
#  datasource:
#    url: jdbc:mysql://{NCP_DB_IP}:3306/{DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: {DB_ID}
#    password: {DB_PW}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#  data:
#    redis:
#      host: {REDIS_IP}
#      port: 6379
#      password: {REDIS_PW}

logging:
  level:
    com.example.LiveHost: debug  # 우리 패키지 로그는 자세히(Debug) 보여줘
    org.hibernate.SQL: debug # 실행되는 SQL 쿼리도 보여줘